apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../
images:
  - name: ghcr.io/jeremiah-k/mmrelay
    # Replace with the digest for the image tag you intend to deploy.
    # Find tags/digests at: https://github.com/jeremiah-k/meshtastic-matrix-relay/pkgs/container/mmrelay
    # Example: skopeo inspect docker://ghcr.io/jeremiah-k/mmrelay:<tag>
    digest: sha256:REPLACE_ME
