apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mmrelay
resources:
  - pvc.yaml
  - networkpolicy.yaml
  - deployment.yaml
images:
  - name: ghcr.io/jeremiah-k/mmrelay
    newTag: 1.2.9
