{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mmrelay.fullname" . }}
  labels:
    {{- include "mmrelay.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "mmrelay.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if hasKey .Values.networkPolicy "ingress" }}
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
    {{- else }}
    []
    {{- end }}
  egress:
    {{- if hasKey .Values.networkPolicy "egress" }}
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
    {{- else }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
        - ipBlock:
            cidr: ::/0
    {{- end }}
{{- end }}
